const products = [
    {
        "id": 1,
        "p_id": 111,
        "title": "BLIVE ",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "/images/products/male/m1.jpg"
    },
    {
        "id": 2,
        "p_id": 222,
        "title": "VeBNoR ",
        "description": "Men Regular Fit Solid Spread Collar Casual Shirt",
        "price": 455,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m2.jpg"
    },
    {
        "id": 3,
        "p_id": 3,
        "title": "Roadster",
        "description": "Men Slim Fit Checkered Casual Shirt",
        "price": 1299,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m3.jpg"
    },
    {
        "id": 4,
        "p_id": 444,
        "title": "Pepzo ",
        "description": "Men Regular Fit Solid Spread Collar Casual Shirt",
        "price": 800,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m4.jpg"
    },
    {
        "id": 5,
        "p_id": 555,
        "title": "Surhi ",
        "description": "Men Slim Fit Checkered Spread Collar Casual Shirt",
        "price": 1400,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m5.jpg"
    },
    {
        "id": 6,
        "p_id": 666,
        "title": "Pepzo",
        "description": "Men Regular Fit Solid Spread Collar Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m6.jpg"
    },
    {
        "id": 7,
        "p_id": 777,
        "title": "Surhi ",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m7.jpg"
    },
    {
        "id": 8,
        "p_id": 888,
        "title": "BLIVE ",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m8.jpg"
    },
    {
        "id": 9,
        "p_id": 999,
        "title": "Surhi ",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m9.jpg"
    },
    {
        "id": 10,
        "p_id": 1000,
        "title": "Surhi",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m10.jpg"
    },
    {
        "id": 11,
        "p_id": 1111,
        "title": "BLIVE ",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m11.jpg"
    },
    {
        "id": 12,
        "p_id": 1222,
        "title": "Surhi ",
        "description": "Men Regular Fit Color Block Casual Shirt",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "",
        "category": "male",
        "thumbnail": "../images/products/male/m12.jpg"
    }
]
module.exports = products